### ISSUE TITLE
Task list for contributors - Lista de tarefas para contribuidores

### ISSUE THREAD

**Issue by lucasfturos** [lucasfturos/API_PlotGraph#2]
### Lista de tarefas

- [ ] Coleta de dados por CLI.
- [ ] Tratamentos de dados.
- [ ] Melhorias nos gráficos.
- [ ] Criar documentação na aba Wiki.
- [ ] Passar o código em inglês.
- [ ] Documentação em Português e em Inglês.

A cada tarefa concluída eu passo o check.
Para criar novas tarefas, comente logo abaixo nesse issues que eu irei na incluir na lista logo acima.

### Task list

- [ ] Data collection via CLI.
- [ ] Data processing.
- [ ] Graphics improvements.
- [ ] Create documentation in the Wiki tab.
- [ ] Pass the code in English.
- [ ] Documentation in Portuguese and English.

With each completed task I pass the check.
To create new tasks, comment below on this issue that I will include in the list above.
